translate = {
  "apple": "olma",
  "make an occusation": "ayblamoq",
  "make a demand": "talab qilmoq",
  "make an announcement": "e'lon qilmoq",
  "make an application": "ariza bermoq",
  "make a list": "roʻyxatga olmoq",
  "make an argument": "kelishmoq",
  "make an attempt": "urunmoq",
  "make a choice": "tanlamoq",
  "make a difference": "farqlamoq",
  "make a remark": "izohlamoq",
  "make a speech": "nutq soʻzlamoq",
  "make a suggestion": "taklif qilmoq",
  "make an affort": "harakat qilmoq",
  "make progress": "ulgurmoq, ildamlash",
  "make a will": "vasiyat qilmoq",
  "make friends": "doʻstlar orttiqmoq",
  "make a comment": "sharxlamoq",
  "make an excuse": "uzr sòramoq",
  "make a money": "pul ishlab topmoq",
  "make a plan": "reja tuzmoq",
  "make a point": "maqsad qilmoq",
  "make a promise": "va'da bermoq",
  "make a mess": "tartibsizlik qilmoq",
  "make a less": "yoʻqotish",
  "make a proposal": "yoʻqotish",
  "make a sound": "ovoz chiqarmoq",
  "call around": "tashrif buyurmoq",
  "call back": "qaytib qo’ng’iroq qilmoq",
  "call on": "yordam so’ramoq",
  "carry off": "g’alaba qilmoq, kasallikdan o’lmoq",
  "catch on": "mashxurlik qozonmoq",
  "charge with": "jinoyatda ayblamoq",
  "cheer up": "undamoq, ruhlantirmoq",
  "chill out": "dam olmoq",
  "clear away": "manzilni tark etish",
  "close up": "to’liq yopish, birlashtirish, yaqinlashish",
  "come down with": "kasal bo’lmoq",
  "cry off": "kelishuvni bekor qilish",
  "take after": "o’xshamoq",
  "tuck away": "xavfsiz joyga qo’yish",
  "turn up": "ovozini ko’tarish, kelish, paydo bo’lish",
  "own up to": "tan olish, bo’yniga olish",
  "opt for": "tanlamoq",
  "reckon on": "eng kamida deb hisoblash",
  "run on": "hisobiga yurmoq",
  "rope in": "kimnidir yordam berishga jalb qilish",
  "set aside": "sudda davo/hukmni bekor qilish",
  "show off": "maqtanib ko’z-ko’z qilmoq",
  "wear out": "tamom bo’lgunicha ishlatish",
  "wear down": "kuchsizlantirish",
  "desire": "istak, hoxish",
  "glory": "sharaf, go'zallik",
  "pumpkin": "qovoq",
  "experience": "tajriba",
  "reconcile": "yarash(tir)moq",
  "astonishing": "hayratda qoldiradigan",
  "child": "bola",
  "sophisticate": "nozik, nafis",
  "regret": "pushaymonlik",
  "rebel": "isyon, isyonchi",
  "tranquil": "bosilgan, vazmin",
  "sunrise": "quyoshning chiqishi",
  "sunset": "quyosh botishi",
  "fabulous": "aqil bovar qilmas",
  "meadow": "o'tloq, yaylov",
  "reflection": "aks, tasir",
  "passion": "ehtiros",
  "umbrella": "soyabon",
  "lollipop": "xo'razqand",
  "banana": "banan",
  "animal": "jonivor",
  "perfection": "mukammalik",
  "mother": "ona",
  "important": "muhim",
  "gorgeous": "juda yaxshi ajoib",
  "sweetheart": "shirin qalb",
  "butterfly": "kapalak",
  "godsend": "g'oyibdan kelgan omad, baxt",
  "unique": "yakkayu yagona",
  "summer": "yoz",
  "ask me another": "Osonroq savol so'ra!", 
  "i don't care": "Menga farqi yo'q",
  "i have no idea": "Bilmasam", 
  "i wish I knew": "Qani, edi bilsaydim!", 
  "it doesn't matter": "farqi yo'q",
  "it doesn't prove a thing": "Bu hech narsani o'zgartira olmaydi", 
  "it's all the same to me": "Hammasi baribir",
  "it's beside the point": "Bu mutloq boshqa narsa",
  "it's up to you": "Sizga bog'liq",
  "let's clear it up": "Keling, aniqlab olamiz", 
  "let's drop the subject": "Keling shu mavzuni to'xtataylik", 
  "so what?": "Nima bo'libdi(farqi nima)?", 
  "that's not the point": "Buning aloqasi yo'q", 
  "that's very well, but": "Ajoyib, lekin....", 
  "use your own judgement": "o'zingga qara",
  "what are you driving at?": "Nima demoqchisiz?", 
  "what are you talking about?": "Nima deyapsiz?", 
  "what for?": "Nima uchun?", 
  "what of it?": "Xo'sh nima bo'libdi?", 
  "you can take it from me": "Menga ishonishingiz mumkin",
  "jewellery": "[ jvalri ] - taqinchoqlar",
  "earrings": "[ ierngs ] - zirak, sirg'a",
  "necklace": "[ nekles ] - marjon, tros",
  "ring": "[ ring ] - uzuk",
  "wrist watch": "[ ristwach ] - qoʻl soati",
  "bracelet": "[ breislet ] - braslet, bilakuzuk",
  "to be thirsty": "[ zso'rsti ] - chanqamoq",
  "insect": "[ insekt ] - hasharot",
  "lie": "[ lay ] - yolg'on",
  "cry": "[ kray ] - yig'lamoq",
  "relatives": "[ relitivs ] - qarindoshlar",
  "husband": "[ hazbend ] - er, qalliq",
  "wife": "[ vayf ] - xotin, rafiq",
  "parent": "[ pernt ] - ota - ona",
  "daughter": "[ dovter ] - qiz farzand",
  son [ san ] - o'g'il farzand
  grandparent [ grendperent ] - bobo-buvi
  granddaughter - [ grenddovter ] - qiz nevara
  grandson [ grendsan ] - o'g'il nevara
  uncle [ ankl ] - amaki, tog'a
  modify [ madifay ] - o'zgartirmoq
  affirmative [ efermedif ] - ijobiy
  description [ diskripshn ] - tasvir, bayon
  event [ ivent ] - voqea, hodisa
  to be cross [ cros ] - jahli chiqmoq
  to be delighted [ dilayted ] - mamnun, xursand bo'lmoq
  to be embarrased [ imbarest ] - xijolat bo'lmoq
  to be disappointed [ disapointed ] - hafsalasi pir bo'lmoq
  to be envious [ envies ] - xasadgo'y bo'lmoq
  to be excited - [ eksayted ] - juda xursand
}
